version: "3.7"

services:
  influxdb:
    image: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=home
    ports:
      - 8086:8086
    volumes:
      - influxdb_volume:/var/lib/influxdb
  chronograf:
    image: chronograf
    restart: always
    ports:
      - 8888:8888
    volumes:
      - chronograf_volume:/var/lib/chronograf
  kapacitor:
    image: kapacitor
    restart: always
    ports:
      - 9092:9092
    environment:
        - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    volumes:
      - kapacitor_volume:/var/lib/kapacitor

volumes:
  influxdb_volume: ~
  chronograf_volume: ~
  kapacitor_volume: ~
